### ISSUE TITLE
Remove Ericsson name from Apache template in readme

### ISSUE THREAD

**Issue by henning-roos** [eiffel-community/eiffel-repository-template#14]
### Description
Change copyright owner from Ericsson to generic copyright owner.

### Motivation
Since it is not only Ericsson that creates new Eiffel repositories we should update the readme file so that a generic copyright owner is provided as per http://www.apache.org/licenses/LICENSE-2.0.

### Exemplification
Copyright [yyyy] [name of copyright owner]

### Benefits
More inclusive community

### Possible Drawbacks
None

**Comment by d-stahl-ericsson** [comment]
To summarize the discussion i Technical Committee:
* The template shouldn't read "Ericsson"
* Files contributed to others should have their copyright statements updated accordingly
* If we want to change actual practice (with regards e.g. to including license notice for READMEs), this is not a problem from a pragmatic point of view, but we need to anchor that with the responsibles within each affected company.

**Comment by magnusbaeck** [comment]
@henning-roos, is there anything more to do before closing this issue? AFAICT all Ericsson references have been removed (except for the one in repo-checklist.md but that's for that file itself).

**Comment by magnusbaeck** [comment]
Assuming this one's done. Feel free to reopen otherwise.
