### ISSUE TITLE
Make a proper template repo out of this repo?

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-repository-template#7]
### Description
Should we make a proper template repo out of this repo as described here: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository?

### Motivation
Make it event easier to set up a new repo in Eiffel Community

### Exemplification
-

### Benefits
Less risk of creating new repos with incorrect file structure

### Possible Drawbacks
None that I know of. We already have the 'eiffel-repository-template' repo, so why not make it a 'template'?

**Comment by e-backmark-ericsson** [comment]
If we do this change, we should update the instruction created in this PR: https://github.com/eiffel-community/community/pull/42

**Comment by e-pettersson-ericsson** [comment]
Sounds like a good idea! Hoewever, I think it is the repo checklist available in this repository that should include an "update CODEOWNERS file" instead of the howto guide in community.

**Comment by e-backmark-ericsson** [comment]
Sure, but the howto guide should not say '_Copy_ the content of ...template' repo, but instead state how you do to create a new repo by using the template repo.

**Comment by e-pettersson-ericsson** [comment]
Ah true.
